defmodule BroadwayUsersWorker do
  use Broadway

  alias Broadway.Message

  def start_link(_opts) do
    Broadway.start_link(BroadwayUsersWorker,
      name: BroadwayUsersWorker,
      producer: [
        module:
          {BroadwaySQS.Producer,
           queue_url: "https://sqs.amazonaws.com/0000000000000/UsersQueue", # Here goes the url generated by amazon
           config: [
             access_key_id: "", # Here is your Access Key ID Generated in the Amazon Cloud Console
             secret_access_key: "", # Here is your Secret Access Key Generated in the Amazon Cloud Console
             region: "sa-east-1" # Here is the region of your SQS server
           ]}
      ],
      processors: [
        default: [] # Here you can add many processors to your message
      ],
      batchers: [ # Here you can add many batchers to your message
        default: [
          batch_size: 10,
          batch_timeout: 2000
        ]
      ]
    )
  end

  @impl true
  def handle_message(_, %Message{} = message, _) do
    message
    |> Message.update_data(&process_data/1)
    |> Message.put_batcher(:default)
  end

  defp process_data(data) do
    data
    |> IO.puts()
    # Do some calculations, generate a JSON representation, etc.
  end

  @impl true
  def handle_batch(:default, messages, _batch_info, _context) do
    messages
    # Add to database, send to another service, etc.
  end


end
